<Project Sdk="Godot.NET.Sdk/3.3.0">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>8.0</LangVersion>
    <RootNamespace>Biosplit2</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Libraries\**\*.cs" />
    <ProjectReference Include="Libraries\Biosplit.Ini\Biosplit.Ini.csproj" />
  </ItemGroup>
</Project>

